title: Groupe Ventclair
description: Luxury home builder in Montreal. Premium materials, expert craftsmanship, accessible pricing.

collections:
  projects:
    output: false
    sort_by: order

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - _style.css
  - .work
  - fonts
  - "Screenshot*"

keep_files:
  - img
  - style.css
