title: Groupe Ventclair
description: Luxury home builder in Montreal. Premium materials, expert
  craftsmanship, accessible pricing.
phone: +1 (888) 889 8335
email: info@groupeventclair.com
address:
  street: 404-5500 avenue Adalbert
  city: Montréal
  province: QC
  postal: H4W 2A9
social:
  facebook: https://www.facebook.com/people/Groupe-Ventclair/61578005243465/
  instagram: https://www.instagram.com/groupe_ventclair/
copyright:
  en: "All rights reserved. R.B.Q : 5720-6864-01"
  fr: "Tous droits réservés. R.B.Q : 5720-6864-01"
